version: '3.7'
services:
  reverse-proxy:
    image: traefik:1.7-alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - ./traefik/log/traefik.log:/traefik.log
      - ./traefik/log/access.log:/access.log


  nginx-personnal-website:
    image: nginx:1.16-alpine
    container_name: nginx-personnal-website
    restart: always
    depends_on:
      - reverse-proxy
      - personnal-website-frontend
      - personnal-website-backend
    labels:
      - traefik.backend=nginx-personnal-website
      - traefik.frontend.rule=Host:ludovic-ortega.adminafk.fr,adminafk.fr,api.adminafk.fr,admin.adminafk.fr
      - traefik.network=proxy
      - traefik.port=80
      - traefik.enable=true
      - traefik.backend.healthcheck.hostname=admin.adminafk.fr
      - traefik.backend.healthcheck.path=/health
      - traefik.backend.healthcheck.intervals=10s
    volumes:
      - ./personnal-website/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./personnal-website/nginx/log/error.log:/var/log/nginx/error.log
      - ./personnal-website/nginx/log/access.log:/var/log/nginx/access.log
      - personnal-website-frontend_static:/opt/services/personnal-website/frontend/static
      - personnal-website-backend_static:/opt/services/personnal-website/backend/static
    networks:
      - proxy


  personnal-website-frontend:
    build: ./personnal-website/frontend/
    container_name: personnal-website-frontend
    volumes:
      - personnal-website-frontend_static:/opt/services/personnal-website/frontend/static
    networks:
      - proxy


  personnal-website-backend:
    build: ./personnal-website/backend/
    command: >
      sh -c "rm -rf ./static/* /opt/services/personnal-website/backend/static/*
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py collectstatic --no-input
      && mkdir -p /opt/services/personnal-website/backend/static/
      && mv ./static/* /opt/services/personnal-website/backend/static/
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: personnal-website-backend
    restart: always
    volumes:
      - personnal-website-backend_static:/opt/services/personnal-website/backend/static
    networks:
      - proxy
    env_file:
      - ./personnal-website/backend/prod.env


networks:
  web:
    external: true

  proxy:
    internal: true


volumes:
  personnal-website-frontend_static:
  personnal-website-backend_static: