version: "2.4"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8000:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    volumes:
      - unifi-storage:/config


volumes:
  unifi-storage: