
version: '3.7'
services:
  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    restart: always
    depends_on:
      - wikijs_db
    labels:
      - traefik.backend=wiki
      - traefik.frontend.rule=Host:wiki.adminafk.fr
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.protocol=http
      - traefik.enable=true
      - traefik.frontend.rateLimit.rateSet.standard.period=10
      - traefik.frontend.rateLimit.rateSet.standard.average=150
      - traefik.frontend.rateLimit.rateSet.standard.burst=300
      - traefik.backend.healthcheck.hostname=wiki.adminafk.fr
      - traefik.backend.healthcheck.path=/login
      - traefik.backend.healthcheck.intervals=10s
    networks:
      - proxy
      - wiki
    env_file:
        - ./wiki/config/prod.env

  wikijs_db:
    image: postgres:11-alpine
    container_name: wikijs_db
    restart: always
    networks:
      - wiki
    env_file:
      - ./wiki/config/prod_db.env
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data


networks:
  proxy:
    external:
      name: proxy

  wiki:
    external:
      name: wiki


volumes:
  db-data: