version: '3.7'
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    restart: always
    depends_on:
      - bookstack_db
    labels:
      - traefik.backend=wiki
      - traefik.frontend.rule=Host:wiki.adminafk.fr
      - traefik.docker.network=proxy
      - traefik.port=443
      - traefik.protocol=https
      - traefik.enable=true
      - traefik.frontend.rateLimit.rateSet.standard.period=10
      - traefik.frontend.rateLimit.rateSet.standard.average=150
      - traefik.frontend.rateLimit.rateSet.standard.burst=300
      - traefik.backend.healthcheck.hostname=wiki.adminafk.fr
      - traefik.backend.healthcheck.path=/login
      - traefik.backend.healthcheck.intervals=10s
    networks:
      - proxy
      - wiki
    env_file:
        - ./wiki/config/prod.env

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    restart: always
    networks:
      - wiki
    env_file:
        - ./wiki/config/prod_db.env


networks:
  proxy:
    external:
      name: proxy

  wiki:
    external:
      name: wiki