version: '3.7'
services:
  grafana:
    image: grafana/grafana:6.3.3
    container_name: grafana
    restart: always
    labels:
      - traefik.backend=monitoring
      - traefik.frontend.rule=Host:monitoring.adminafk.fr
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.enable=true
      - traefik.frontend.rateLimit.rateSet.standard.period=10
      - traefik.frontend.rateLimit.rateSet.standard.average=150
      - traefik.frontend.rateLimit.rateSet.standard.burst=300
      - traefik.backend.healthcheck.hostname=monitoring.adminafk.fr
      - traefik.backend.healthcheck.path=/login
      - traefik.backend.healthcheck.intervals=10s
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards/:/var/lib/grafana/dashboards
    networks:
      - proxy
      - web
      - monitoring
    env_file:
      - ./monitoring/grafana/prod.env

  prometheus:
    image: prom/prometheus:v2.11.2
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/etc/prometheus
    networks:
      - proxy
      - monitoring

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    depends_on:
      - redis
    networks:
      - monitoring

  redis:
    image: redis:5.0.5-alpine3.10
    container_name: redis
    restart: always
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.7.7
    container_name: influxdb
    restart: always
    ports:
      - "8089:8089/udp"
    volumes:
      - ./monitoring/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-storage:/var/lib/influxdb
    networks:
      - monitoring
    env_file:
      - ./monitoring/influxdb/prod.env

  unifi-poller:
    image: golift/unifi-poller:1.5.1
    container_name: unifi-poller
    restart: always
    volumes:
      - ./monitoring/unifi-poller/up.conf:/etc/unifi-poller/up.conf
    networks:
      - monitoring


networks:
  web:
    external:
      name: web

  proxy:
    external:
      name: proxy

  monitoring:
    external:
      name: monitoring

volumes:
  prometheus-storage:
  influxdb-storage: