version: '3.7'
services:
  nginx-personnal-website:
    image: nginx:1.17.3-alpine
    container_name: nginx-personnal-website
    restart: always
    depends_on:
      - personnal-website-frontend
      - personnal-website-backend
    labels:
      - traefik.backend=personnal-website
      - traefik.frontend.rule=Host:ludovic-ortega.adminafk.fr,adminafk.fr,api.adminafk.fr,admin.adminafk.fr
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.enable=true
      - traefik.frontend.rateLimit.rateSet.standard.period=10
      - traefik.frontend.rateLimit.rateSet.standard.average=150
      - traefik.frontend.rateLimit.rateSet.standard.burst=300
      - traefik.backend.healthcheck.hostname=admin.adminafk.fr
      - traefik.backend.healthcheck.path=/admin/
      - traefik.backend.healthcheck.intervals=10s
    volumes:
      - ./personnal-website/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/opt/services/frontend/static
      - backend_static:/opt/services/backend/static
    networks:
      - proxy
      - personnal-website

  personnal-website-frontend:
    image: monsterrr/personnal-website:frontend-latest
    container_name: personnal-website-frontend
    volumes:
      - frontend_static:/opt/services/frontend/static
    networks:
      - personnal-website

  personnal-website-backend:
    image: monsterrr/personnal-website:backend-latest
    command: >
      sh -c "rm -rf ./static/* /opt/services/backend/static/*
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py collectstatic --no-input
      && mkdir -p /opt/services/backend/static/
      && mv ./static/* /opt/services/backend/static/
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: personnal-website-backend
    restart: always
    volumes:
      - backend_static:/opt/services/backend/static
    networks:
      - personnal-website
    env_file:
      - ./personnal-website/backend/prod.env


networks:
  proxy:
    external:
      name: proxy

  personnal-website:
    external:
      name: personnal-website

volumes:
  frontend_static:
  backend_static: