version: "3.7"
services:
  cachet:
    build:
      context: ./status/Docker/
      args:
        - cachet_ver=2.4
    container_name: cachet
    restart: always
    depends_on:
      - cachet_db
    labels:
      - traefik.backend=status
      - traefik.frontend.rule=Host:status.adminafk.fr
      - traefik.docker.network=proxy
      - traefik.port=8000
      - traefik.enable=true
      - traefik.frontend.rateLimit.rateSet.standard.period=10
      - traefik.frontend.rateLimit.rateSet.standard.average=150
      - traefik.frontend.rateLimit.rateSet.standard.burst=300
    networks:
      - proxy
      - status
    environment:
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_DEBUG=false
      - APP_ENV=production
      - DEBUG=false
      - DB_DRIVER=pgsql
      - DB_HOST=cachet_db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_PREFIX=chq_
      - SESSION_DRIVER=file
      - SESSION_DOMAIN=status.adminafk.fr
      - MAIL_DRIVER=smtp
      - MAIL_HOST=adminafk.fr
      - MAIL_PORT=587
      - MAIL_USERNAME=contact@adminafk.fr
      - MAIL_ADDRESS=contact@adminafk.fr
      - MAIL_ENCRYPTION=tls

  cachet_db:
    image: postgres:9.5
    container_name: cachet_db
    restart: always
    volumes:
      - cachet:/var/lib/postgresql/data
    networks:
      - status
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=


networks:
  proxy:
    external:
      name: proxy

  status:
    external:
      name: status


volumes:
  cachet: