apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 2

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true

- name: Loki
  type: loki
  access: proxy
  orgId: 2
  url: http://loki:3100
  jsonData:
      maxLines: 1000