apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: InfluxDB
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true

- name: InfluxDB
  type: influxdb
  access: proxy
  database: proxmox
  user: grafana
  password: grafana
  url: http://influxdb:8086
  jsonData:
    httpMode: GET